DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 2.0  # 0.55 (Robot Specs: 0.70)
  min_vel_x: 0.0 

  max_vel_y: 0.0  # diff drive robot
  min_vel_y: 0.0  # diff drive robot

  # The velocity when robot is moving in a straight line
  max_vel_trans: 2.0 # choose slightly less than the base's capability
  min_vel_trans: 0.0  # this is the min trans velocity when there is negligible rotational velocity

  max_vel_theta: 0.5  # choose slightly less than the base's capability
  min_vel_theta: 0.0  # this is the min angular velocity when there is negligible translational velocity
  
  acc_lim_x: 1.0 # maximum is theoretically 2.0
  acc_lim_y: 0.0     # diff drive robot
  acc_lim_th: 1.0

# Goal Tolerance Parameters
  yaw_goal_tolerance: 0.05 # 0.05
  xy_goal_tolerance: 0.10  # 0.10
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 3.0       # 1.7
  sim_granularity: 0.025  # step size, in meters, to take between points on a given trajectory
  vx_samples: 20       # 3
  vy_samples: 0       # diff drive robot, there is only one sample
  vth_samples: 40
  controller_frequency: 20.0

# Trajectory Scoring Parameters
  path_distance_bias: 24.0     # 32.0   - weighting for how much it should stick to the global path plan
  goal_distance_bias: 24.0      # 24.0   - wighting for how much it should attempt to reach its goal
  occdist_scale: 0.16            # 0.01   - weighting for how much the controller should avoid obstacles
  forward_point_distance: 0.325 # 0.325  - how far along to place an additional scoring point
  stop_time_buffer: 0.2         # 0.2    - amount of time a robot must stop in before colliding for a valid traj.
  scaling_speed: 2.5           # 0.25   - absolute velocity at which to start scaling the robot's footprint
  max_scaling_factor: 0.2       # 0.2    - how much to scale the robot's footprint when at speed.
  publish_cost_grid: false

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05  # 0.05   - how far to travel before resetting oscillation flags

# Debugging
  publish_traj_pc: True
  publish_cost_grid_pc: True
  # global_frame_id: odom