global_costmap:
  global_frame: map
  robot_base_frame: $(arg base_frame)
  update_frequency: 10.0
  publish_frequency: 10.0
  # static_map: true
 
  transform_tolerance: 0.5
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
